

jobs:
- job: test_logic_app
  displayName: Test logic app workflow
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    

  - task: NodeTool@0 
    inputs:
        versionSpec: 14.x
  - bash: |
          sudo npm install -g azurite@3.20.1
          sudo azurite -v
          sudo mkdir azurite
          sudo azurite --silent --location azurite --debug azurite\debug.log &
    displayName: 'Install and Run Azurite'

  - task: PowerShell@2
    displayName: 'Install Azure Function Core Tools'
    inputs:
      targetType: 'inline'
      script: |
              sudo apt-get install azure-functions-core-tools-4 -y
#              sudo npm i -g azure-functions-core-tools@4 --unsafe-perm true

  - task: PowerShell@2
    displayName: 'Run Azure Function Core Tools'
    inputs:
      targetType: 'inline'
      script: |
              Install-Package PInvoke
              func start --verbose
